TRAINING:
  SOFT_AUG: False
  BATCH_SIZE: 10
  TEST_BATCH_SIZE: 10
  N_TRIPLETS: 4
  MIN_KEYPOINTS_PER_IMAGE: 4
  MIN_KEYPOINTS_PER_IMAGE_PAIR: 4
TEST:
  TEST_BATCH_SIZE: 10
BLOBINATOR:
  BLOB_SHEET: "blobs.pdf"
  MAX_ROTATION: 90
  MIN_SCALE: 0.2
  MAX_SCALE:  0.8
  MAX_WIGGLE: 0.2